# Generated by Django 4.1.1 on 2022-10-04 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_especialidad', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prioridad', models.CharField(default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=40)),
                ('codigo_proyecto', models.CharField(max_length=5)),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha inicio')),
                ('fecha_culminacion', models.DateTimeField(verbose_name='Fecha culminacion')),
                ('descripcion', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_rol', models.CharField(default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_status', models.CharField(default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=40)),
                ('codigo_area', models.CharField(max_length=5)),
                ('id_proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.proyecto')),
            ],
        ),
    ]
