# Generated by Django 4.1.2 on 2022-11-07 19:02

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0005_events_middlewareevents'),
        ('HelpdeskApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ejemplo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('edad', models.IntegerField(verbose_name='edad')),
            ],
        ),
        migrations.CreateModel(
            name='EjemploEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('edad', models.IntegerField(verbose_name='edad')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event', to='HelpdeskApp.ejemplo')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ejemplo',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_ejemploevent" ("edad", "id", "nombre", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."edad", NEW."id", NEW."nombre", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id"); RETURN NULL;', hash='72f29d5bec685a04de07a13b7412571c6d3538a9', operation='INSERT', pgid='pgtrigger_snapshot_insert_e9640', table='HelpdeskApp_ejemplo', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ejemplo',
            trigger=pgtrigger.compiler.Trigger(name='snapshot_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "HelpdeskApp_ejemploevent" ("edad", "id", "nombre", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."edad", NEW."id", NEW."nombre", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id"); RETURN NULL;', hash='99875fb6c94354c30e48038ee88f8d2ffd06689b', operation='UPDATE', pgid='pgtrigger_snapshot_update_e86c1', table='HelpdeskApp_ejemplo', when='AFTER')),
        ),
    ]
