# Generated by Django 4.1 on 2022-11-11 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AUDIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('accion', models.CharField(max_length=100)),
                ('id_status_e', models.BigIntegerField(null=True)),
                ('id_proyecto', models.BigIntegerField(null=True)),
                ('id_area', models.BigIntegerField(null=True)),
                ('id_rol', models.BigIntegerField(null=True)),
                ('id_especialidad', models.BigIntegerField(null=True)),
                ('id_usuario', models.BigIntegerField(null=True)),
                ('id_especialista', models.BigIntegerField(null=True)),
                ('id_prioridad', models.BigIntegerField(null=True)),
                ('id_status_ticket', models.BigIntegerField(null=True)),
                ('id_ticket', models.BigIntegerField(null=True)),
                ('id_comentario', models.BigIntegerField(null=True)),
                ('fecha_creacion', models.DateTimeField(null=True)),
                ('fecha_actualizacion', models.DateTimeField(null=True)),
                ('fecha_culminacion', models.DateTimeField(null=True)),
            ],
        ),
    ]
