# Generated by Django 4.1.2 on 2022-10-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fecha_asignado',
            field=models.DateTimeField(verbose_name='Fecha asignado'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_atendido',
            field=models.DateTimeField(verbose_name='Fecha atendido'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_cancelado',
            field=models.DateTimeField(verbose_name='Fecha cancelado'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_proceso',
            field=models.DateTimeField(verbose_name='Fecha proceso'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_resuelto',
            field=models.DateTimeField(verbose_name='Fecha resuelto'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_validado',
            field=models.DateTimeField(verbose_name='Fecha validado'),
        ),
    ]
