# Generated by Django 4.1 on 2022-11-15 23:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0005_events_middlewareevents'),
        ('HelpdeskApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria_Area',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('codigo_area', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Auditoria_Comentario',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('fecha_culminacion', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Auditoria_Especialidad',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('tipo_especialidad', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_culminacion', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Auditoria_Especialista',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_culminacion', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Auditoria_Prioridad',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('tipo_prioridad', models.CharField(choices=[('Urgente', 'Urgente'), ('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Urgente', max_length=50)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_culminacion', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Auditoria_Proyecto',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('codigo_proyecto', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_culminacion', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Auditoria_Rol',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('tipo_rol', models.CharField(choices=[('SA', 'Super Administrador'), ('GP', 'Gestor proyecto'), ('ES', 'Especialista'), ('UF', 'Operador')], default='SA', max_length=2)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_culminacion', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Auditoria_Status_E',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('tipo_estatus', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=50)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha incial')),
                ('fecha_actualizacion', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Auditoria_Status_Ticket',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('tipo_estatus', models.CharField(choices=[('Creado', 'Creado'), ('Atendido', 'Atendido'), ('Asignado', 'Asignado'), ('Proceso', 'Proceso'), ('Espera', 'Espera'), ('Resuelto', 'Resuelto'), ('Validado', 'Validado'), ('Cancelado', 'Cancelado'), ('Reasignado', 'Reasignado')], default='Creado', max_length=10)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Auditoria_Ticket',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('folio', models.CharField(max_length=20)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha creacion')),
                ('fecha_validado', models.DateTimeField(null=True, verbose_name='Fecha validado')),
                ('fecha_cancelado', models.DateTimeField(null=True, verbose_name='Fecha cancelado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Auditoria_Usuarios',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('codigo_usuario', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Historial_Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='area',
            trigger=pgtrigger.compiler.Trigger(name='Inserci_n', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_area" ("codigo_area", "fecha_actualizacion", "fecha_creacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."codigo_area", NEW."fecha_actualizacion", NEW."fecha_creacion", NEW."id", _pgh_attach_context(), NOW(), \'Inserción\', NEW."id"); RETURN NULL;', hash='7c31758a3c4a453f67fe1fe06f1b6613dbb4910c', operation='INSERT', pgid='pgtrigger_inserci_n_5318a', table='HelpdeskApp_area', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='area',
            trigger=pgtrigger.compiler.Trigger(name='Antes_de_Actualizar', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_area" ("codigo_area", "fecha_actualizacion", "fecha_creacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."codigo_area", OLD."fecha_actualizacion", OLD."fecha_creacion", OLD."id", _pgh_attach_context(), NOW(), \'Antes de Actualizar\', OLD."id"); RETURN NULL;', hash='fa9caf91b3c0e8e68b53a4ec8a03b091625f5034', operation='UPDATE', pgid='pgtrigger_antes_de_actualizar_1e3a2', table='HelpdeskApp_area', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='area',
            trigger=pgtrigger.compiler.Trigger(name='Actualizaci_n', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_area" ("codigo_area", "fecha_actualizacion", "fecha_creacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."codigo_area", NEW."fecha_actualizacion", NEW."fecha_creacion", NEW."id", _pgh_attach_context(), NOW(), \'Actualización\', NEW."id"); RETURN NULL;', hash='664086d9e1b3d43e83b362a8195f13c357fe65a1', operation='UPDATE', pgid='pgtrigger_actualizaci_n_c18f0', table='HelpdeskApp_area', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='area',
            trigger=pgtrigger.compiler.Trigger(name='Antes_de_Eliminar', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_area" ("codigo_area", "fecha_actualizacion", "fecha_creacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."codigo_area", OLD."fecha_actualizacion", OLD."fecha_creacion", OLD."id", _pgh_attach_context(), NOW(), \'Antes de Eliminar\', OLD."id"); RETURN NULL;', hash='57d359f1a40f5c6f7b2ecdaabcfd45e25a82298e', operation='DELETE', pgid='pgtrigger_antes_de_eliminar_888cc', table='HelpdeskApp_area', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='comentario',
            trigger=pgtrigger.compiler.Trigger(name='Inserci_n', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_comentario" ("fecha_creacion", "fecha_culminacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."fecha_creacion", NEW."fecha_culminacion", NEW."id", _pgh_attach_context(), NOW(), \'Inserción\', NEW."id"); RETURN NULL;', hash='530d1c7391bbaf6c8357565816e51d6b6a0ccfa9', operation='INSERT', pgid='pgtrigger_inserci_n_57b11', table='HelpdeskApp_comentario', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='comentario',
            trigger=pgtrigger.compiler.Trigger(name='Antes_de_Actualizar', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_comentario" ("fecha_creacion", "fecha_culminacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."fecha_creacion", OLD."fecha_culminacion", OLD."id", _pgh_attach_context(), NOW(), \'Antes de Actualizar\', OLD."id"); RETURN NULL;', hash='7d562bd67bbd06c566d1a0ce32a365760ad1d713', operation='UPDATE', pgid='pgtrigger_antes_de_actualizar_e2005', table='HelpdeskApp_comentario', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='comentario',
            trigger=pgtrigger.compiler.Trigger(name='Actualizaci_n', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_comentario" ("fecha_creacion", "fecha_culminacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."fecha_creacion", NEW."fecha_culminacion", NEW."id", _pgh_attach_context(), NOW(), \'Actualización\', NEW."id"); RETURN NULL;', hash='874ba4c09b9f867d3f5ba3f6f716c1b5af06808d', operation='UPDATE', pgid='pgtrigger_actualizaci_n_dc7f7', table='HelpdeskApp_comentario', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='comentario',
            trigger=pgtrigger.compiler.Trigger(name='Antes_de_Eliminar', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_comentario" ("fecha_creacion", "fecha_culminacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."fecha_creacion", OLD."fecha_culminacion", OLD."id", _pgh_attach_context(), NOW(), \'Antes de Eliminar\', OLD."id"); RETURN NULL;', hash='50f760e1870ab2057476f02171bd849d6c1248db', operation='DELETE', pgid='pgtrigger_antes_de_eliminar_dbbb5', table='HelpdeskApp_comentario', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='especialidad',
            trigger=pgtrigger.compiler.Trigger(name='Inserci_n', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_especialidad" ("fecha_creacion", "fecha_culminacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tipo_especialidad") VALUES (NEW."fecha_creacion", NEW."fecha_culminacion", NEW."id", _pgh_attach_context(), NOW(), \'Inserción\', NEW."id", NEW."tipo_especialidad"); RETURN NULL;', hash='92c18fc36dc2d18c88a0de2ba6bfd8f8cf5b9602', operation='INSERT', pgid='pgtrigger_inserci_n_1f193', table='HelpdeskApp_especialidad', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='especialidad',
            trigger=pgtrigger.compiler.Trigger(name='Antes_de_Actualizar', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_especialidad" ("fecha_creacion", "fecha_culminacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tipo_especialidad") VALUES (OLD."fecha_creacion", OLD."fecha_culminacion", OLD."id", _pgh_attach_context(), NOW(), \'Antes de Actualizar\', OLD."id", OLD."tipo_especialidad"); RETURN NULL;', hash='136d175197605c6942825256ed55acd35d458522', operation='UPDATE', pgid='pgtrigger_antes_de_actualizar_2afb5', table='HelpdeskApp_especialidad', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='especialidad',
            trigger=pgtrigger.compiler.Trigger(name='Actualizaci_n', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_especialidad" ("fecha_creacion", "fecha_culminacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tipo_especialidad") VALUES (NEW."fecha_creacion", NEW."fecha_culminacion", NEW."id", _pgh_attach_context(), NOW(), \'Actualización\', NEW."id", NEW."tipo_especialidad"); RETURN NULL;', hash='189ec555125d08e324b4fa7b72d513e059354f7b', operation='UPDATE', pgid='pgtrigger_actualizaci_n_47618', table='HelpdeskApp_especialidad', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='especialidad',
            trigger=pgtrigger.compiler.Trigger(name='Antes_de_Eliminar', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_especialidad" ("fecha_creacion", "fecha_culminacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tipo_especialidad") VALUES (OLD."fecha_creacion", OLD."fecha_culminacion", OLD."id", _pgh_attach_context(), NOW(), \'Antes de Eliminar\', OLD."id", OLD."tipo_especialidad"); RETURN NULL;', hash='d216805bd661b8d3b72477ecab573eec3915f22e', operation='DELETE', pgid='pgtrigger_antes_de_eliminar_f5414', table='HelpdeskApp_especialidad', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='especialista',
            trigger=pgtrigger.compiler.Trigger(name='Inserci_n', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_especialista" ("fecha_creacion", "fecha_culminacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."fecha_creacion", NEW."fecha_culminacion", NEW."id", _pgh_attach_context(), NOW(), \'Inserción\', NEW."id"); RETURN NULL;', hash='8457b9cf43361435919e437e181b9d8e9a4425b5', operation='INSERT', pgid='pgtrigger_inserci_n_f32aa', table='"HelpdeskApp_Especialista"', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='especialista',
            trigger=pgtrigger.compiler.Trigger(name='Antes_de_Actualizar', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_especialista" ("fecha_creacion", "fecha_culminacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."fecha_creacion", OLD."fecha_culminacion", OLD."id", _pgh_attach_context(), NOW(), \'Antes de Actualizar\', OLD."id"); RETURN NULL;', hash='2057e237a143e1a3a3e7076c565f47ebdb146318', operation='UPDATE', pgid='pgtrigger_antes_de_actualizar_88b3d', table='"HelpdeskApp_Especialista"', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='especialista',
            trigger=pgtrigger.compiler.Trigger(name='Actualizaci_n', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_especialista" ("fecha_creacion", "fecha_culminacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."fecha_creacion", NEW."fecha_culminacion", NEW."id", _pgh_attach_context(), NOW(), \'Actualización\', NEW."id"); RETURN NULL;', hash='7311562a93bfc67da7a0d267c7fe228bcfec7ec8', operation='UPDATE', pgid='pgtrigger_actualizaci_n_cadd7', table='"HelpdeskApp_Especialista"', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='especialista',
            trigger=pgtrigger.compiler.Trigger(name='Antes_de_Eliminar', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_especialista" ("fecha_creacion", "fecha_culminacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."fecha_creacion", OLD."fecha_culminacion", OLD."id", _pgh_attach_context(), NOW(), \'Antes de Eliminar\', OLD."id"); RETURN NULL;', hash='d98e5867c4673ace02fa60ad42cd0a8264f6f2cd', operation='DELETE', pgid='pgtrigger_antes_de_eliminar_bfa60', table='"HelpdeskApp_Especialista"', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='prioridad',
            trigger=pgtrigger.compiler.Trigger(name='Inserci_n', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_prioridad" ("fecha_creacion", "fecha_culminacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tipo_prioridad") VALUES (NEW."fecha_creacion", NEW."fecha_culminacion", NEW."id", _pgh_attach_context(), NOW(), \'Inserción\', NEW."id", NEW."tipo_prioridad"); RETURN NULL;', hash='8ef529bc0bedba7befcba940ae157b77e7c19540', operation='INSERT', pgid='pgtrigger_inserci_n_fd06f', table='HelpdeskApp_prioridad', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='prioridad',
            trigger=pgtrigger.compiler.Trigger(name='Antes_de_Actualizar', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_prioridad" ("fecha_creacion", "fecha_culminacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tipo_prioridad") VALUES (OLD."fecha_creacion", OLD."fecha_culminacion", OLD."id", _pgh_attach_context(), NOW(), \'Antes de Actualizar\', OLD."id", OLD."tipo_prioridad"); RETURN NULL;', hash='7cdba0d32605ebe7da91df88d183521d785f3a0b', operation='UPDATE', pgid='pgtrigger_antes_de_actualizar_3de90', table='HelpdeskApp_prioridad', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='prioridad',
            trigger=pgtrigger.compiler.Trigger(name='Actualizaci_n', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_prioridad" ("fecha_creacion", "fecha_culminacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tipo_prioridad") VALUES (NEW."fecha_creacion", NEW."fecha_culminacion", NEW."id", _pgh_attach_context(), NOW(), \'Actualización\', NEW."id", NEW."tipo_prioridad"); RETURN NULL;', hash='9ffcb4d45ea18cf1b441bfd86b4b941e03728c70', operation='UPDATE', pgid='pgtrigger_actualizaci_n_50e93', table='HelpdeskApp_prioridad', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='prioridad',
            trigger=pgtrigger.compiler.Trigger(name='Antes_de_Eliminar', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_prioridad" ("fecha_creacion", "fecha_culminacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tipo_prioridad") VALUES (OLD."fecha_creacion", OLD."fecha_culminacion", OLD."id", _pgh_attach_context(), NOW(), \'Antes de Eliminar\', OLD."id", OLD."tipo_prioridad"); RETURN NULL;', hash='16c21f8c7e5a79957ffc4e5082f99f2138473f00', operation='DELETE', pgid='pgtrigger_antes_de_eliminar_be85d', table='HelpdeskApp_prioridad', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='proyecto',
            trigger=pgtrigger.compiler.Trigger(name='Inserci_n', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_proyecto" ("codigo_proyecto", "fecha_creacion", "fecha_culminacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."codigo_proyecto", NEW."fecha_creacion", NEW."fecha_culminacion", NEW."id", _pgh_attach_context(), NOW(), \'Inserción\', NEW."id"); RETURN NULL;', hash='c0e7b598e3f1613742e70fa8c42502abfe5f1d72', operation='INSERT', pgid='pgtrigger_inserci_n_e720e', table='HelpdeskApp_proyecto', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='proyecto',
            trigger=pgtrigger.compiler.Trigger(name='Antes_de_Actualizar', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_proyecto" ("codigo_proyecto", "fecha_creacion", "fecha_culminacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."codigo_proyecto", OLD."fecha_creacion", OLD."fecha_culminacion", OLD."id", _pgh_attach_context(), NOW(), \'Antes de Actualizar\', OLD."id"); RETURN NULL;', hash='a46fe01bd5c09dd5d7a17876058be5db6d11e4ed', operation='UPDATE', pgid='pgtrigger_antes_de_actualizar_e32cf', table='HelpdeskApp_proyecto', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='proyecto',
            trigger=pgtrigger.compiler.Trigger(name='Actualizaci_n', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_proyecto" ("codigo_proyecto", "fecha_creacion", "fecha_culminacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."codigo_proyecto", NEW."fecha_creacion", NEW."fecha_culminacion", NEW."id", _pgh_attach_context(), NOW(), \'Actualización\', NEW."id"); RETURN NULL;', hash='2bae19b3098f6339c624f8cf64d75e0ed148391c', operation='UPDATE', pgid='pgtrigger_actualizaci_n_12669', table='HelpdeskApp_proyecto', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='proyecto',
            trigger=pgtrigger.compiler.Trigger(name='Antes_de_Eliminar', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_proyecto" ("codigo_proyecto", "fecha_creacion", "fecha_culminacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."codigo_proyecto", OLD."fecha_creacion", OLD."fecha_culminacion", OLD."id", _pgh_attach_context(), NOW(), \'Antes de Eliminar\', OLD."id"); RETURN NULL;', hash='bca61163fce7d7233427d068dc5ddd613a681240', operation='DELETE', pgid='pgtrigger_antes_de_eliminar_c296e', table='HelpdeskApp_proyecto', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='rol',
            trigger=pgtrigger.compiler.Trigger(name='Inserci_n', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_rol" ("fecha_creacion", "fecha_culminacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tipo_rol") VALUES (NEW."fecha_creacion", NEW."fecha_culminacion", NEW."id", _pgh_attach_context(), NOW(), \'Inserción\', NEW."id", NEW."tipo_rol"); RETURN NULL;', hash='e682fc331470141a03f3fa4b48df26f2cd624629', operation='INSERT', pgid='pgtrigger_inserci_n_15994', table='HelpdeskApp_rol', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='rol',
            trigger=pgtrigger.compiler.Trigger(name='Antes_de_Actualizar', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_rol" ("fecha_creacion", "fecha_culminacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tipo_rol") VALUES (OLD."fecha_creacion", OLD."fecha_culminacion", OLD."id", _pgh_attach_context(), NOW(), \'Antes de Actualizar\', OLD."id", OLD."tipo_rol"); RETURN NULL;', hash='fb2f67efe15229782b60266ce70c85b8a91f84bd', operation='UPDATE', pgid='pgtrigger_antes_de_actualizar_8a0c5', table='HelpdeskApp_rol', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='rol',
            trigger=pgtrigger.compiler.Trigger(name='Actualizaci_n', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_rol" ("fecha_creacion", "fecha_culminacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tipo_rol") VALUES (NEW."fecha_creacion", NEW."fecha_culminacion", NEW."id", _pgh_attach_context(), NOW(), \'Actualización\', NEW."id", NEW."tipo_rol"); RETURN NULL;', hash='24a28731c61853a7be963c4199b74180a0340849', operation='UPDATE', pgid='pgtrigger_actualizaci_n_86f2d', table='HelpdeskApp_rol', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='rol',
            trigger=pgtrigger.compiler.Trigger(name='Antes_de_Eliminar', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_rol" ("fecha_creacion", "fecha_culminacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tipo_rol") VALUES (OLD."fecha_creacion", OLD."fecha_culminacion", OLD."id", _pgh_attach_context(), NOW(), \'Antes de Eliminar\', OLD."id", OLD."tipo_rol"); RETURN NULL;', hash='4cdf71d89b7bfc2b54d865940e8678f092680215', operation='DELETE', pgid='pgtrigger_antes_de_eliminar_a1c60', table='HelpdeskApp_rol', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='status_e',
            trigger=pgtrigger.compiler.Trigger(name='Inserci_n', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_status_e" ("fecha_actualizacion", "fecha_creacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tipo_estatus") VALUES (NEW."fecha_actualizacion", NEW."fecha_creacion", NEW."id", _pgh_attach_context(), NOW(), \'Inserción\', NEW."id", NEW."tipo_estatus"); RETURN NULL;', hash='73682115f90cf58ce4e2d588413150c1ab849094', operation='INSERT', pgid='pgtrigger_inserci_n_442b2', table='HelpdeskApp_status_e', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='status_e',
            trigger=pgtrigger.compiler.Trigger(name='Antes_de_Actualizar', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_status_e" ("fecha_actualizacion", "fecha_creacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tipo_estatus") VALUES (OLD."fecha_actualizacion", OLD."fecha_creacion", OLD."id", _pgh_attach_context(), NOW(), \'Antes de Actualizar\', OLD."id", OLD."tipo_estatus"); RETURN NULL;', hash='da902444869d204290f38fdfe552d01ebe3ffde0', operation='UPDATE', pgid='pgtrigger_antes_de_actualizar_f08ad', table='HelpdeskApp_status_e', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='status_e',
            trigger=pgtrigger.compiler.Trigger(name='Actualizaci_n', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_status_e" ("fecha_actualizacion", "fecha_creacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tipo_estatus") VALUES (NEW."fecha_actualizacion", NEW."fecha_creacion", NEW."id", _pgh_attach_context(), NOW(), \'Actualización\', NEW."id", NEW."tipo_estatus"); RETURN NULL;', hash='c722dbc62e760e29d2370d4a10eaea9953c7f1b2', operation='UPDATE', pgid='pgtrigger_actualizaci_n_2b0de', table='HelpdeskApp_status_e', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='status_e',
            trigger=pgtrigger.compiler.Trigger(name='Antes_de_Eliminar', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_status_e" ("fecha_actualizacion", "fecha_creacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tipo_estatus") VALUES (OLD."fecha_actualizacion", OLD."fecha_creacion", OLD."id", _pgh_attach_context(), NOW(), \'Antes de Eliminar\', OLD."id", OLD."tipo_estatus"); RETURN NULL;', hash='630fac4ffd3834b6325544cee14330425a2de5ae', operation='DELETE', pgid='pgtrigger_antes_de_eliminar_867ff', table='HelpdeskApp_status_e', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='status_ticket',
            trigger=pgtrigger.compiler.Trigger(name='Inserci_n', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_status_ticket" ("fecha_creacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tipo_estatus") VALUES (NEW."fecha_creacion", NEW."id", _pgh_attach_context(), NOW(), \'Inserción\', NEW."id", NEW."tipo_estatus"); RETURN NULL;', hash='cbc7a3af4979f999881e63ccb8b487cba4a8bb3a', operation='INSERT', pgid='pgtrigger_inserci_n_11a50', table='HelpdeskApp_status_ticket', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='status_ticket',
            trigger=pgtrigger.compiler.Trigger(name='Antes_de_Actualizar', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_status_ticket" ("fecha_creacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tipo_estatus") VALUES (OLD."fecha_creacion", OLD."id", _pgh_attach_context(), NOW(), \'Antes de Actualizar\', OLD."id", OLD."tipo_estatus"); RETURN NULL;', hash='7cfb0f5cf5c6aa1874314e442bb32569dba3d3c9', operation='UPDATE', pgid='pgtrigger_antes_de_actualizar_edafb', table='HelpdeskApp_status_ticket', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='status_ticket',
            trigger=pgtrigger.compiler.Trigger(name='Actualizaci_n', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_status_ticket" ("fecha_creacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tipo_estatus") VALUES (NEW."fecha_creacion", NEW."id", _pgh_attach_context(), NOW(), \'Actualización\', NEW."id", NEW."tipo_estatus"); RETURN NULL;', hash='4e81ea05a07130b71898b56d14c194493311714b', operation='UPDATE', pgid='pgtrigger_actualizaci_n_11c32', table='HelpdeskApp_status_ticket', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='status_ticket',
            trigger=pgtrigger.compiler.Trigger(name='Antes_de_Eliminar', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_status_ticket" ("fecha_creacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tipo_estatus") VALUES (OLD."fecha_creacion", OLD."id", _pgh_attach_context(), NOW(), \'Antes de Eliminar\', OLD."id", OLD."tipo_estatus"); RETURN NULL;', hash='166ad78641d42f828b7b5dbfa833217175ce6b5e', operation='DELETE', pgid='pgtrigger_antes_de_eliminar_786f1', table='HelpdeskApp_status_ticket', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ticket',
            trigger=pgtrigger.compiler.Trigger(name='Inserci_n', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_ticket" ("fecha_cancelado", "fecha_validado", "folio", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "publish") VALUES (NEW."fecha_cancelado", NEW."fecha_validado", NEW."folio", NEW."id", _pgh_attach_context(), NOW(), \'Inserción\', NEW."id", NEW."publish"); RETURN NULL;', hash='77b30780a71bd2c183305c358d36b5fe460dd63c', operation='INSERT', pgid='pgtrigger_inserci_n_de98d', table='HelpdeskApp_ticket', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ticket',
            trigger=pgtrigger.compiler.Trigger(name='Antes_de_Actualizar', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_ticket" ("fecha_cancelado", "fecha_validado", "folio", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "publish") VALUES (OLD."fecha_cancelado", OLD."fecha_validado", OLD."folio", OLD."id", _pgh_attach_context(), NOW(), \'Antes de Actualizar\', OLD."id", OLD."publish"); RETURN NULL;', hash='37e2a610b69beec26e06e47f5df6e3b5ee60506a', operation='UPDATE', pgid='pgtrigger_antes_de_actualizar_13c9e', table='HelpdeskApp_ticket', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ticket',
            trigger=pgtrigger.compiler.Trigger(name='Actualizaci_n', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_ticket" ("fecha_cancelado", "fecha_validado", "folio", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "publish") VALUES (NEW."fecha_cancelado", NEW."fecha_validado", NEW."folio", NEW."id", _pgh_attach_context(), NOW(), \'Actualización\', NEW."id", NEW."publish"); RETURN NULL;', hash='aa1d1fa18d62c59ad7cf00a5a8a0adb2cdeb5c04', operation='UPDATE', pgid='pgtrigger_actualizaci_n_40cd0', table='HelpdeskApp_ticket', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ticket',
            trigger=pgtrigger.compiler.Trigger(name='Antes_de_Eliminar', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_ticket" ("fecha_cancelado", "fecha_validado", "folio", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "publish") VALUES (OLD."fecha_cancelado", OLD."fecha_validado", OLD."folio", OLD."id", _pgh_attach_context(), NOW(), \'Antes de Eliminar\', OLD."id", OLD."publish"); RETURN NULL;', hash='88eab26128173430e13984aac079fb964435acf4', operation='DELETE', pgid='pgtrigger_antes_de_eliminar_444c4', table='HelpdeskApp_ticket', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='usuario',
            trigger=pgtrigger.compiler.Trigger(name='Inserci_n', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_usuarios" ("codigo_usuario", "fecha_creacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."codigo_usuario", NEW."fecha_creacion", NEW."id", _pgh_attach_context(), NOW(), \'Inserción\', NEW."id"); RETURN NULL;', hash='fc89762f87c4f3f3b4c24a52139bf2def7cccff9', operation='INSERT', pgid='pgtrigger_inserci_n_048f5', table='HelpdeskApp_usuario', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='usuario',
            trigger=pgtrigger.compiler.Trigger(name='Antes_de_Actualizar', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_usuarios" ("codigo_usuario", "fecha_creacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."codigo_usuario", OLD."fecha_creacion", OLD."id", _pgh_attach_context(), NOW(), \'Antes de Actualizar\', OLD."id"); RETURN NULL;', hash='aba1d8af47b8d3c10ce4516f3f68ff33841f40e1', operation='UPDATE', pgid='pgtrigger_antes_de_actualizar_5290a', table='HelpdeskApp_usuario', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='usuario',
            trigger=pgtrigger.compiler.Trigger(name='Actualizaci_n', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_usuarios" ("codigo_usuario", "fecha_creacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."codigo_usuario", NEW."fecha_creacion", NEW."id", _pgh_attach_context(), NOW(), \'Actualización\', NEW."id"); RETURN NULL;', hash='d91c725bc2f51d2a711a9b7193bffbaf193a2323', operation='UPDATE', pgid='pgtrigger_actualizaci_n_592df', table='HelpdeskApp_usuario', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='usuario',
            trigger=pgtrigger.compiler.Trigger(name='Antes_de_Eliminar', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_usuarios" ("codigo_usuario", "fecha_creacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."codigo_usuario", OLD."fecha_creacion", OLD."id", _pgh_attach_context(), NOW(), \'Antes de Eliminar\', OLD."id"); RETURN NULL;', hash='a598f597d71bb34a6e0aebc12d94a5b4943a82a7', operation='DELETE', pgid='pgtrigger_antes_de_eliminar_3ab93', table='HelpdeskApp_usuario', when='AFTER')),
        ),
        migrations.AddField(
            model_name='historial_ticket',
            name='id_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ticket', to='HelpdeskApp.ticket'),
        ),
        migrations.AddField(
            model_name='historial_ticket',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to='HelpdeskApp.usuario'),
        ),
        migrations.AddField(
            model_name='auditoria_usuarios',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='auditoria_usuarios',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_codigo_usuario_fecha_creacion_event', to='HelpdeskApp.usuario'),
        ),
        migrations.AddField(
            model_name='auditoria_ticket',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='auditoria_ticket',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_folio_publish_fecha_validado_fecha_cancelado_event', to='HelpdeskApp.ticket'),
        ),
        migrations.AddField(
            model_name='auditoria_status_ticket',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='auditoria_status_ticket',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_tipo_estatus_fecha_creacion_event', to='HelpdeskApp.status_ticket'),
        ),
        migrations.AddField(
            model_name='auditoria_status_e',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='auditoria_status_e',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_tipo_estatus_fecha_creacion_fecha_actualizacion_event', to='HelpdeskApp.status_e'),
        ),
        migrations.AddField(
            model_name='auditoria_rol',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='auditoria_rol',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_tipo_rol_fecha_creacion_fecha_culminacion_event', to='HelpdeskApp.rol'),
        ),
        migrations.AddField(
            model_name='auditoria_proyecto',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='auditoria_proyecto',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_codigo_proyecto_fecha_creacion_fecha_culminacion_event', to='HelpdeskApp.proyecto'),
        ),
        migrations.AddField(
            model_name='auditoria_prioridad',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='auditoria_prioridad',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_tipo_prioridad_fecha_creacion_fecha_culminacion_event', to='HelpdeskApp.prioridad'),
        ),
        migrations.AddField(
            model_name='auditoria_especialista',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='auditoria_especialista',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_fecha_creacion_fecha_culminacion_event', to='HelpdeskApp.especialista'),
        ),
        migrations.AddField(
            model_name='auditoria_especialidad',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='auditoria_especialidad',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_tipo_especialidad_fecha_creacion_fecha_culminacion_event', to='HelpdeskApp.especialidad'),
        ),
        migrations.AddField(
            model_name='auditoria_comentario',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='auditoria_comentario',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_fecha_creacion_fecha_culminacion_event', to='HelpdeskApp.comentario'),
        ),
        migrations.AddField(
            model_name='auditoria_area',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='auditoria_area',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_codigo_area_fecha_creacion_fecha_actualizacion_event', to='HelpdeskApp.area'),
        ),
    ]
