# Generated by Django 4.1.1 on 2022-10-21 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=100)),
                ('codigo_proyecto', models.CharField(max_length=10, unique=True)),
                ('fecha_inicial', models.DateTimeField(auto_now_add=True, verbose_name='Fecha incial del proyecto')),
                ('fecha_final', models.DateTimeField(auto_now=True, verbose_name='Fecha final del proyecto')),
                ('descripcion', models.TextField(null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_culminacion', models.DateTimeField(auto_now=True)),
                ('status_entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.status_e')),
            ],
        ),
    ]
