# Generated by Django 4.1.1 on 2022-10-04 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='id_proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.proyecto'),
        ),
    ]
