# Generated by Django 4.1.1 on 2022-11-07 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='area_proyecto',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha creacion'),
        ),
    ]
