# Generated by Django 4.1.1 on 2022-10-10 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='historial_ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(verbose_name='Fecha modificacion')),
                ('id_especialidad_anterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.especialidad')),
                ('id_status_anterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.status')),
                ('id_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.ticket')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.usuario')),
            ],
        ),
    ]
