# Generated by Django 4.1.2 on 2022-11-07 20:45

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0002_ejemplo_ejemploevent_ejemplo_snapshot_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='ejemplo',
            name='snapshot_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='ejemplo',
            name='snapshot_update',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ejemplo',
            trigger=pgtrigger.compiler.Trigger(name='afterinsertorupdate', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_ejemploevent" ("edad", "id", "nombre", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."edad", NEW."id", NEW."nombre", _pgh_attach_context(), NOW(), \'afterinsertorupdate\', NEW."id"); RETURN NULL;', hash='af842dcc95dcc8b08d79e1797017772ab2621080', operation='INSERT OR UPDATE', pgid='pgtrigger_afterinsertorupdate_28e49', table='HelpdeskApp_ejemplo', when='AFTER')),
        ),
    ]
