# Generated by Django 4.1.1 on 2022-11-07 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0002_remove_area_area_proyecto_alter_ticket_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='area_proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.proyecto'),
        ),
    ]
