# Generated by Django 4.1.1 on 2022-10-21 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0002_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=10)),
                ('codigo_area', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.TextField(null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('area_proyecto', models.ManyToManyField(to='HelpdeskApp.proyecto')),
                ('status_entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.status_e')),
            ],
        ),
    ]
