# Generated by Django 4.1.2 on 2022-10-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0002_alter_ticket_fecha_asignado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='comentario_t',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='coordenadas',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_asignado',
            field=models.DateTimeField(null=True, verbose_name='Fecha asignado'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_atendido',
            field=models.DateTimeField(null=True, verbose_name='Fecha atendido'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_cancelado',
            field=models.DateTimeField(null=True, verbose_name='Fecha cancelado'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_proceso',
            field=models.DateTimeField(null=True, verbose_name='Fecha proceso'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_resuelto',
            field=models.DateTimeField(null=True, verbose_name='Fecha resuelto'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_validado',
            field=models.DateTimeField(null=True, verbose_name='Fecha validado'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_superior',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
