# Generated by Django 4.1 on 2022-11-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0002_auditoria_area_auditoria_comentario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100, null=True)),
                ('id_ticket', models.BigIntegerField(null=True)),
                ('id_usuario', models.BigIntegerField(null=True)),
                ('id_especialita', models.BigIntegerField(null=True)),
                ('id_estatus_ticket', models.BigIntegerField(null=True)),
                ('fecha_modificacion', models.DateTimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Historial_Ticket',
        ),
    ]
