# Generated by Django 4.1.2 on 2022-11-11 22:50

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0005_events_middlewareevents'),
        ('HelpdeskApp', '0002_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ejemplo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('edad', models.IntegerField(null=True, verbose_name='edad')),
            ],
        ),
        migrations.CreateModel(
            name='EjemploEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('edad', models.IntegerField(null=True, verbose_name='edad')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event', to='HelpdeskApp.ejemplo')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ejemplo',
            trigger=pgtrigger.compiler.Trigger(name='Inserci_n', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_ejemploevent" ("edad", "id", "nombre", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."edad", NEW."id", NEW."nombre", _pgh_attach_context(), NOW(), \'Inserción\', NEW."id"); RETURN NULL;', hash='93f510264e150c53d950f80c776fb6f1904ab194', operation='INSERT', pgid='pgtrigger_inserci_n_02223', table='HelpdeskApp_ejemplo', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ejemplo',
            trigger=pgtrigger.compiler.Trigger(name='Antes_de_Actualizar', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_ejemploevent" ("edad", "id", "nombre", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."edad", OLD."id", OLD."nombre", _pgh_attach_context(), NOW(), \'Antes de Actualizar\', OLD."id"); RETURN NULL;', hash='3cad1924f56bd54556f74a16ab63e60629f6f46d', operation='UPDATE', pgid='pgtrigger_antes_de_actualizar_372e8', table='HelpdeskApp_ejemplo', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ejemplo',
            trigger=pgtrigger.compiler.Trigger(name='Actualizaci_n', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_ejemploevent" ("edad", "id", "nombre", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."edad", NEW."id", NEW."nombre", _pgh_attach_context(), NOW(), \'Actualización\', NEW."id"); RETURN NULL;', hash='49782495634679e5995d06570df9bd09079af65a', operation='UPDATE', pgid='pgtrigger_actualizaci_n_482d7', table='HelpdeskApp_ejemplo', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ejemplo',
            trigger=pgtrigger.compiler.Trigger(name='Antes_de_Eliminar', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_ejemploevent" ("edad", "id", "nombre", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."edad", OLD."id", OLD."nombre", _pgh_attach_context(), NOW(), \'Antes de Eliminar\', OLD."id"); RETURN NULL;', hash='ed5bf4096e975ce3b3847b70cc6d2049bdceadda', operation='DELETE', pgid='pgtrigger_antes_de_eliminar_d85a0', table='HelpdeskApp_ejemplo', when='AFTER')),
        ),
    ]
