# Generated by Django 4.1 on 2022-11-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0002_auditoria_area_auditoria_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial_ticket',
            name='especialita',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historial_ticket',
            name='estatus_ticket',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
