# Generated by Django 4.1 on 2022-11-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0003_historial_ticket_especialita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_ticket',
            name='id_ticket',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historial_ticket',
            name='id_usuario',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
