# Generated by Django 4.1.1 on 2022-10-07 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0003_status_e_remove_area_id_proyecto_delete_especialidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicial', models.DateTimeField(auto_created=True, verbose_name='Fecha incial')),
                ('nombre_proyecto', models.CharField(max_length=10)),
                ('codigo_proyecto', models.CharField(max_length=5)),
                ('fecha_final', models.DateTimeField(verbose_name='Fecha final')),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_culminacion', models.DateTimeField()),
                ('status_entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.status_e')),
            ],
        ),
    ]
