# Generated by Django 4.1.2 on 2022-10-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0003_alter_ticket_comentario_t_alter_ticket_coordenadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='evidencias',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
