# Generated by Django 4.1.2 on 2022-11-07 20:48

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0003_remove_ejemplo_snapshot_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='ejemplo',
            trigger=pgtrigger.compiler.Trigger(name='beforedelete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_ejemploevent" ("edad", "id", "nombre", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."edad", OLD."id", OLD."nombre", _pgh_attach_context(), NOW(), \'beforedelete\', OLD."id"); RETURN NULL;', hash='efb274e6e24ecebe5ffadc0426a18f9fc1d0c73a', operation='DELETE', pgid='pgtrigger_beforedelete_22eb3', table='HelpdeskApp_ejemplo', when='AFTER')),
        ),
    ]
