# Generated by Django 4.1 on 2022-11-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0003_historial_delete_historial_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria_ticket',
            name='fecha_cancelado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha cancelado'),
        ),
        migrations.AlterField(
            model_name='auditoria_ticket',
            name='fecha_validado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha validado'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_asignado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha asignado'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_atendido',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha atendido'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_cancelado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha cancelado'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_proceso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha proceso'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_resuelto',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha resuelto'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_validado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha validado'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_superior',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
