# Generated by Django 4.1.2 on 2022-11-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0004_alter_ticket_evidencias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status_e',
            name='fecha_culminacion',
        ),
        migrations.AddField(
            model_name='status_e',
            name='fecha_actualizacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='status_e',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha incial'),
        ),
        migrations.AlterField(
            model_name='status_e',
            name='tipo_estatus',
            field=models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='Inactivo', max_length=50),
        ),
    ]
