# Generated by Django 4.1.2 on 2022-11-07 20:58

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0004_ejemplo_beforedelete'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='ejemplo',
            trigger=pgtrigger.compiler.Trigger(name='beforeupdate', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_ejemploevent" ("edad", "id", "nombre", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."edad", OLD."id", OLD."nombre", _pgh_attach_context(), NOW(), \'beforeupdate\', OLD."id"); RETURN NULL;', hash='89f8087c0ae2377f14fc9e755228caf29df7cdc3', operation='UPDATE', pgid='pgtrigger_beforeupdate_e536a', table='HelpdeskApp_ejemplo', when='AFTER')),
        ),
    ]
