# Generated by Django 4.1 on 2022-11-16 22:39

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0004_alter_auditoria_ticket_fecha_cancelado_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='usuario',
            name='Inserci_n',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='usuario',
            name='Antes_de_Actualizar',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='usuario',
            name='Actualizaci_n',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='usuario',
            name='Antes_de_Eliminar',
        ),
        migrations.AddField(
            model_name='auditoria_usuarios',
            name='fecha_actulizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_actulizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditoria_area',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditoria_comentario',
            name='fecha_culminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditoria_especialidad',
            name='fecha_culminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditoria_especialista',
            name='fecha_culminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditoria_prioridad',
            name='fecha_culminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditoria_proyecto',
            name='fecha_culminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditoria_rol',
            name='fecha_culminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditoria_status_e',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditoria_usuarios',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_codigo_usuario_fecha_creacion_fecha_actulizacion_event', to='HelpdeskApp.usuario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha_culminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='fecha_culminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='especialista_usuario',
            field=models.ForeignKey(blank=True, db_column='especialista_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.usuario', verbose_name='especialista_u'),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='fecha_culminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prioridad',
            name='fecha_culminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_culminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_final',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha final del proyecto'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='fecha_culminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='status_e',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='usuario',
            trigger=pgtrigger.compiler.Trigger(name='Inserci_n', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_usuarios" ("codigo_usuario", "fecha_actulizacion", "fecha_creacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."codigo_usuario", NEW."fecha_actulizacion", NEW."fecha_creacion", NEW."id", _pgh_attach_context(), NOW(), \'Inserción\', NEW."id"); RETURN NULL;', hash='83a9e8054594c5c8282ca11b10d78624b4e4146c', operation='INSERT', pgid='pgtrigger_inserci_n_048f5', table='HelpdeskApp_usuario', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='usuario',
            trigger=pgtrigger.compiler.Trigger(name='Antes_de_Actualizar', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_usuarios" ("codigo_usuario", "fecha_actulizacion", "fecha_creacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."codigo_usuario", OLD."fecha_actulizacion", OLD."fecha_creacion", OLD."id", _pgh_attach_context(), NOW(), \'Antes de Actualizar\', OLD."id"); RETURN NULL;', hash='b37dc7d0c1b387ee8746b016b9b89313a60e7343', operation='UPDATE', pgid='pgtrigger_antes_de_actualizar_5290a', table='HelpdeskApp_usuario', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='usuario',
            trigger=pgtrigger.compiler.Trigger(name='Actualizaci_n', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_usuarios" ("codigo_usuario", "fecha_actulizacion", "fecha_creacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."codigo_usuario", NEW."fecha_actulizacion", NEW."fecha_creacion", NEW."id", _pgh_attach_context(), NOW(), \'Actualización\', NEW."id"); RETURN NULL;', hash='ddb8c3792a7e5ca3bdca9d69da62c04ba073f2bd', operation='UPDATE', pgid='pgtrigger_actualizaci_n_592df', table='HelpdeskApp_usuario', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='usuario',
            trigger=pgtrigger.compiler.Trigger(name='Antes_de_Eliminar', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_auditoria_usuarios" ("codigo_usuario", "fecha_actulizacion", "fecha_creacion", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."codigo_usuario", OLD."fecha_actulizacion", OLD."fecha_creacion", OLD."id", _pgh_attach_context(), NOW(), \'Antes de Eliminar\', OLD."id"); RETURN NULL;', hash='49c36705b715ab9ecc4beb57c67ed41d7d4b42b5', operation='DELETE', pgid='pgtrigger_antes_de_eliminar_3ab93', table='HelpdeskApp_usuario', when='AFTER')),
        ),
    ]
