# Generated by Django 4.1.1 on 2022-10-21 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0004_rol_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_usuario', models.CharField(max_length=20, unique=True)),
                ('nombre_usuario', models.TextField(max_length=50, verbose_name='Nombre usuario')),
                ('apellidos_usuario', models.TextField(max_length=100, verbose_name='Apellidos')),
                ('email_usuario', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('password', models.CharField(max_length=8, verbose_name='Contraseña')),
                ('status_entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.status_e')),
                ('usuario_area', models.ManyToManyField(to='HelpdeskApp.area', verbose_name='Área')),
                ('usuario_proyecto', models.ManyToManyField(to='HelpdeskApp.proyecto', verbose_name='Proyecto')),
                ('usuario_rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.rol', verbose_name='Rol')),
            ],
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_culminacion', models.DateTimeField(auto_now=True)),
                ('especialista_especialidad', models.ManyToManyField(to='HelpdeskApp.especialidad')),
                ('especialista_usuario', models.ForeignKey(db_column='especialista_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='HelpdeskApp.usuario', verbose_name='especialista_u')),
                ('status_entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='HelpdeskApp.status_e')),
            ],
            options={
                'db_table': '"HelpdeskApp_Especialista"',
            },
        ),
    ]
