# Generated by Django 4.1 on 2022-11-15 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0004_alter_historial_ticket_id_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_ticket',
            name='id_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.ticket'),
        ),
        migrations.AlterField(
            model_name='historial_ticket',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.usuario'),
        ),
    ]
