# Generated by Django 4.1.1 on 2022-10-07 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0004_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicial', models.DateTimeField(auto_created=True, verbose_name='Fecha en la que se creo el area')),
                ('nombre_area', models.CharField(max_length=10)),
                ('codigo_area', models.CharField(max_length=5)),
                ('fecha_final', models.DateTimeField(verbose_name='Fecha final')),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_culminacion', models.DateTimeField()),
                ('area_proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.proyecto')),
                ('status_entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.status_e')),
            ],
        ),
    ]
