# Generated by Django 4.1.1 on 2022-10-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0005_usuario_especialista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prioridad', models.CharField(choices=[('Urgente', 'Urgente'), ('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Urgente', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_culminacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status_Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_estatus', models.CharField(choices=[('Creado', 'Creado'), ('Atendido', 'Atendido'), ('Asignado', 'Asignado'), ('Proceso', 'Proceso'), ('Espera', 'Espera'), ('Resuelto', 'Resuelto'), ('Validado', 'Validado'), ('Cancelado', 'Cancelado'), ('Reasignado', 'Reasignado')], default='Creado', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_culminacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
