# Generated by Django 4.1 on 2022-11-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0005_remove_usuario_inserci_n_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fecha_espera',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha espera'),
        ),
    ]
