# Generated by Django 4.1.2 on 2022-11-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0005_ejemplo_beforeupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplo',
            name='edad',
            field=models.IntegerField(null=True, verbose_name='edad'),
        ),
        migrations.AlterField(
            model_name='ejemploevent',
            name='edad',
            field=models.IntegerField(null=True, verbose_name='edad'),
        ),
    ]
