# Generated by Django 4.1.2 on 2022-11-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0005_remove_status_e_fecha_culminacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_culminacion',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='codigo_proyecto',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_actualizacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_final',
            field=models.DateTimeField(null=True, verbose_name='Fecha final del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicial',
            field=models.DateTimeField(null=True, verbose_name='Fecha incial'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre_proyecto',
            field=models.CharField(max_length=150),
        ),
    ]
