# Generated by Django 4.1 on 2022-11-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0006_ticket_fecha_espera'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='fecha_actulizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='fecha_culminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='usuario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
