# Generated by Django 4.1.1 on 2022-10-21 16:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0006_prioridad_status_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=250)),
                ('excerpt', models.TextField(null=True, verbose_name='Extracto')),
                ('slug', models.SlugField(max_length=250, null=True, unique_for_date='publish')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha actual')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Activo/Inactivo')),
                ('coordenadas', models.CharField(max_length=30)),
                ('evidencias', models.BinaryField()),
                ('descripcion', models.TextField(null=True)),
                ('comentario_t', models.TextField(verbose_name='Comentario')),
                ('fecha_atendido', models.DateTimeField(verbose_name='Fecha atendido')),
                ('fecha_asignado', models.DateTimeField(verbose_name='Fecha asignado')),
                ('fecha_proceso', models.DateTimeField(verbose_name='Fecha proceso')),
                ('fecha_resuelto', models.DateTimeField(verbose_name='Fecha resuelto')),
                ('fecha_validado', models.DateTimeField(verbose_name='Fecha validado')),
                ('fecha_cancelado', models.DateTimeField(verbose_name='Fecha cancelado')),
                ('ticket_superior', models.BigIntegerField()),
                ('ticket_areaorigen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.area', verbose_name='Área')),
                ('ticket_especialistaas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.especialista', verbose_name='Especialista')),
                ('ticket_proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.proyecto', verbose_name='Proyecto')),
                ('ticket_tipoprioridad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.prioridad', verbose_name='Prioridad')),
                ('ticket_tipostatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.status_ticket', verbose_name='Status')),
                ('ticket_usario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.usuario', verbose_name='Usuario')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Evidencia_Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidencia', models.BinaryField()),
                ('evidencia_ticket', models.ManyToManyField(to='HelpdeskApp.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_comentario', models.DateTimeField(default=django.utils.timezone.now)),
                ('contenido_ticket', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_culminacion', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
                ('comentario_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.ticket')),
                ('comentario_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='HelpdeskApp.usuario')),
            ],
        ),
    ]
