# Generated by Django 4.1.2 on 2022-11-07 21:26

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0007_remove_ejemplo_afterinsertorupdate_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='ejemplo',
            name='Despues_de_Insertar_o_Actualizar',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ejemplo',
            trigger=pgtrigger.compiler.Trigger(name='Inserci_n', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_ejemploevent" ("edad", "id", "nombre", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."edad", NEW."id", NEW."nombre", _pgh_attach_context(), NOW(), \'Inserción\', NEW."id"); RETURN NULL;', hash='93f510264e150c53d950f80c776fb6f1904ab194', operation='INSERT', pgid='pgtrigger_inserci_n_02223', table='HelpdeskApp_ejemplo', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ejemplo',
            trigger=pgtrigger.compiler.Trigger(name='Actualizaci_n', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "HelpdeskApp_ejemploevent" ("edad", "id", "nombre", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."edad", NEW."id", NEW."nombre", _pgh_attach_context(), NOW(), \'Actualización\', NEW."id"); RETURN NULL;', hash='49782495634679e5995d06570df9bd09079af65a', operation='UPDATE', pgid='pgtrigger_actualizaci_n_482d7', table='HelpdeskApp_ejemplo', when='AFTER')),
        ),
    ]
