# Generated by Django 4.1.1 on 2022-10-07 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0007_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_usuario', models.CharField(max_length=5)),
                ('nombre_usuario', models.CharField(max_length=30, verbose_name='Nombre del usuario')),
                ('apellidos_usuario', models.CharField(max_length=30, verbose_name='Appellios del usuario')),
                ('email_usuario', models.EmailField(max_length=254, verbose_name='Nombre del usuario')),
                ('password', models.CharField(max_length=8)),
                ('status_entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.status_e')),
                ('usuario_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.area')),
                ('usuario_especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.especialidad')),
                ('usuario_proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.proyecto')),
                ('usuario_rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.rol')),
            ],
        ),
    ]
