# Generated by Django 4.1.1 on 2022-10-21 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0007_ticket_evidencia_ticket_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_especialistaas',
            new_name='ticket_especialista',
        ),
        migrations.AlterField(
            model_name='especialista',
            name='especialista_usuario',
            field=models.ForeignKey(db_column='especialista_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.usuario', verbose_name='especialista_u'),
        ),
    ]
