# Generated by Django 4.1.1 on 2022-10-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0008_rename_ticket_especialistaas_ticket_ticket_especialista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='evidencias',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to='evidencias/'),
        ),
    ]
