# Generated by Django 4.1.2 on 2022-11-07 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0008_remove_ejemplo_despues_de_insertar_o_actualizar_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='status_e',
            new_name='estatus_e',
        ),
        migrations.RenameModel(
            old_name='status_ticket',
            new_name='estatus_ticket',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='status_entidad',
            new_name='estatus_entidad',
        ),
        migrations.RenameField(
            model_name='especialista',
            old_name='status_entidad',
            new_name='estatus_entidad',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='status_entidad',
            new_name='estatus_entidad',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_tipostatus',
            new_name='estatus',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='status',
            new_name='estatus_entidad',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='status_entidad',
            new_name='estatus_entidad',
        ),
    ]
