# Generated by Django 4.1.1 on 2022-10-07 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0009_area_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_culminacion', models.DateTimeField()),
                ('especialista_especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.especialidad')),
                ('especialista_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.usuario')),
                ('status_entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.status_e')),
            ],
        ),
    ]
