# Generated by Django 4.1 on 2022-11-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0009_bitacora_ticket_superior'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='fecha_asignado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='fecha_atendido',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='fecha_cancelado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='fecha_espera',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='fecha_proceso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='fecha_resuelto',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='fecha_validado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='publish',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
