# Generated by Django 4.1 on 2022-11-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0010_bitacora_fecha_asignado_bitacora_fecha_atendido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='respaldo',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
