# Generated by Django 4.1.1 on 2022-10-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0010_especialista'),
    ]

    operations = [
        migrations.CreateModel(
            name='prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prioridad', models.CharField(choices=[('1', 'Urgente'), ('2', 'Alta'), ('3', 'Media'), ('4', 'Baja')], default='1', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_culminacion', models.DateTimeField()),
            ],
        ),
    ]
