# Generated by Django 4.1.3 on 2022-12-05 18:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0011_alter_bitacora_status_alter_respaldo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='coordenadas',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=6362),
        ),
    ]
