# Generated by Django 4.1.1 on 2022-10-07 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0012_status_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_created=True, verbose_name='Fecha creacion del ticket')),
                ('folio', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=5)),
                ('coordenadas', models.CharField(max_length=30)),
                ('evidencias', models.ImageField(upload_to='')),
                ('descripcion', models.CharField(max_length=100)),
                ('comentario_t', models.CharField(max_length=100)),
                ('fecha_atendido', models.DateTimeField(verbose_name='Fecha atendido')),
                ('fecha_asignado', models.DateTimeField(verbose_name='Fecha asignado')),
                ('fecha_proceso', models.DateTimeField(verbose_name='Fecha proceso')),
                ('fecha_espera', models.DateTimeField(verbose_name='Fecha espera')),
                ('fecha_resuelto', models.DateTimeField(verbose_name='Fecha resuelto')),
                ('fecha_validado', models.DateTimeField(verbose_name='Fecha validado')),
                ('fecha_cancelado', models.DateTimeField(verbose_name='Fecha cancelado')),
                ('ticket_superior', models.BigIntegerField()),
                ('ticket_areaorigen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.area')),
                ('ticket_especialistaasignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.especialista')),
                ('ticket_proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.proyecto')),
                ('ticket_tipoprioridad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.prioridad')),
                ('ticket_tipostatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.status_ticket')),
                ('ticket_usariocreador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.usuario')),
            ],
        ),
    ]
