# Generated by Django 4.1.1 on 2022-10-10 17:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0015_historial_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='fecha_culminacion',
        ),
        migrations.RemoveField(
            model_name='area',
            name='fecha_final',
        ),
        migrations.RemoveField(
            model_name='area',
            name='fecha_inicial',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='fecha_espera',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_especialidad',
        ),
        migrations.AddField(
            model_name='area',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='area',
            name='area_proyecto',
        ),
        migrations.AlterField(
            model_name='area',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='HelpdeskApp.usuario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha_comentario',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='fecha_culminacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='especialista',
            name='especialista_usuario',
        ),
        migrations.AlterField(
            model_name='especialista',
            name='fecha_culminacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='prioridad',
            name='fecha_culminacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_culminacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_final',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha final'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicial',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha incial'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre_proyecto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rol',
            name='fecha_culminacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='status_e',
            name='fecha_culminacion',
            field=models.DateTimeField(default=True),
        ),
        migrations.AlterField(
            model_name='status_ticket',
            name='fecha_culminacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='comentario_t',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_asignado',
            field=models.DateTimeField(default=True, verbose_name='Fecha asignado'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_atendido',
            field=models.DateTimeField(default=True, verbose_name='Fecha atendido'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_cancelado',
            field=models.DateTimeField(default=True, verbose_name='Fecha cancelado'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion del ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_proceso',
            field=models.DateTimeField(default=True, verbose_name='Fecha proceso'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_resuelto',
            field=models.DateTimeField(default=True, verbose_name='Fecha resuelto'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_validado',
            field=models.DateTimeField(default=True, verbose_name='Fecha validado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidos_usuario',
            field=models.CharField(max_length=50, verbose_name='Appellios del usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo_usuario',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(max_length=50, verbose_name='Nombre del usuario'),
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_area',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_proyecto',
        ),
        migrations.DeleteModel(
            name='area_usuario',
        ),
        migrations.AddField(
            model_name='area',
            name='area_proyecto',
            field=models.ManyToManyField(to='HelpdeskApp.proyecto'),
        ),
        migrations.AddField(
            model_name='especialista',
            name='especialista_usuario',
            field=models.ManyToManyField(to='HelpdeskApp.usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario_area',
            field=models.ManyToManyField(to='HelpdeskApp.area'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario_proyecto',
            field=models.ManyToManyField(to='HelpdeskApp.proyecto'),
        ),
    ]
