# Generated by Django 4.1.1 on 2022-10-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0016_remove_area_fecha_culminacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='tipo_especialidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidos_usuario',
            field=models.CharField(max_length=50, verbose_name='Apellidos del usuario'),
        ),
    ]
