# Generated by Django 4.1.1 on 2022-10-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0018_alter_status_e_tipo_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_e',
            name='tipo_estatus',
            field=models.CharField(max_length=100),
        ),
    ]
