# Generated by Django 4.1.1 on 2022-10-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0019_alter_status_e_tipo_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_e',
            name='fecha_culminacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email_usuario',
            field=models.EmailField(max_length=254, verbose_name='Correo'),
        ),
    ]
