# Generated by Django 4.1.1 on 2022-10-11 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0020_alter_status_e_fecha_culminacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial_ticket',
            name='especialista_anterior',
        ),
        migrations.RemoveField(
            model_name='status_e',
            name='fecha_culminacion',
        ),
        migrations.AddField(
            model_name='especialidad',
            name='proyecto_especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.proyecto'),
        ),
        migrations.AddField(
            model_name='status_e',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha final'),
        ),
        migrations.AlterField(
            model_name='area',
            name='codigo_area',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.RemoveField(
            model_name='especialista',
            name='especialista_especialidad',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='codigo_proyecto',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_final',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha final del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicial',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha incial del proyecto'),
        ),
        migrations.AlterField(
            model_name='status_e',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha incial'),
        ),
        migrations.AlterField(
            model_name='status_e',
            name='tipo_estatus',
            field=models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='folio',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo_usuario',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email_usuario',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=8, verbose_name='Ingrese su contraseña'),
        ),
        migrations.AddField(
            model_name='especialista',
            name='especialista_especialidad',
            field=models.ManyToManyField(to='HelpdeskApp.especialidad'),
        ),
    ]
