# Generated by Django 4.1.1 on 2022-10-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0021_remove_historial_ticket_especialista_anterior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='evidencias',
            field=models.BinaryField(),
        ),
        migrations.CreateModel(
            name='evidencia_ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidencia', models.BinaryField()),
                ('evidencia_ticket', models.ManyToManyField(to='HelpdeskApp.ticket')),
            ],
        ),
    ]
