# Generated by Django 4.1.1 on 2022-10-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0024_alter_status_e_tipo_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_e',
            name='tipo_estatus',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], max_length=50),
        ),
    ]
