# Generated by Django 4.1.1 on 2022-10-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0026_alter_ticket_fecha_asignado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prioridad',
            name='tipo_prioridad',
            field=models.CharField(choices=[('Urgente', 'Urgente'), ('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Urgente', max_length=50),
        ),
    ]
