# Generated by Django 4.1.1 on 2022-10-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0027_alter_prioridad_tipo_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_e',
            name='tipo_estatus',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=50),
        ),
    ]
