# Generated by Django 4.1.1 on 2022-10-11 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0029_alter_status_ticket_tipo_estatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_especialistaasignado',
            new_name='ticket_especialistaas',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_usariocreador',
            new_name='ticket_usario',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre_proyecto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidos_usuario',
            field=models.TextField(max_length=100, verbose_name='Apellidos del usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.TextField(max_length=50, verbose_name='Nombre del usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_area',
            field=models.ManyToManyField(to='HelpdeskApp.area', verbose_name='Ingresa tu área'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_proyecto',
            field=models.ManyToManyField(to='HelpdeskApp.proyecto', verbose_name='Ingresa el proyecto al que perteneces'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpdeskApp.rol', verbose_name='Tipo de rol'),
        ),
    ]
