# Generated by Django 4.1.1 on 2022-10-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0030_rename_ticket_especialistaasignado_ticket_ticket_especialistaas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('echa_creacion', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.TextField()),
            ],
        ),
    ]
