# Generated by Django 4.1.1 on 2022-10-11 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0031_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contenido',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='echa_creacion',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='titulo',
            new_name='title',
        ),
    ]
