# Generated by Django 4.1.1 on 2022-10-11 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelpdeskApp', '0032_rename_contenido_post_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='post',
        ),
    ]
